# Vectors and Matrices
## In NumPy

- Add two Python list together does not do vector addition...

In [2]:
u = [1,5,2,9] 
v = [3,6,0,-5]
print("v + u = ", v + u)

v + u =  [3, 6, 0, -5, 1, 5, 2, 9]


- Fortunately, people have provided open-source packages for linear algebra operations in Python

In [3]:
import numpy as np

## Vectors

In [4]:
v = np.array([1,5,2,9])
u = np.array([3,6,0,-5])

# vector addition
print("v+u = ", v+u)

# vector scaling
print("3v = ", 3*v)

# Dot-Product
print("u dot v = ", np.dot(u,v))
print('Or u dot v = ', u.dot(v))

# Length / L2 Norm of a vector
print("sqrt(v dot v) = %.2f" % np.sqrt(np.dot(v,v)))
print("||v|| = %.2f" % np.linalg.norm(v))

v+u =  [ 4 11  2  4]
3v =  [ 3 15  6 27]
u dot v =  -12
Or u dot v =  -12
sqrt(v dot v) = 10.54
||v|| = 10.54


## Matrices

In [5]:
M = np.array([ [1,9,-12], [15, -2, 0] ])
print("M = ", M.shape)
print(M)

# matrix addition
A = np.array([ [1, 1], [2, 1] ])
B = np.array([ [0, 8], [7, 11] ])
print("A+B = \n", A+B) # '\n' is the newline character

# matrix scaling
a = 5
print("aB = \n", a*B)

M =  (2, 3)
[[  1   9 -12]
 [ 15  -2   0]]
A+B = 
 [[ 1  9]
 [ 9 12]]
aB = 
 [[ 0 40]
 [35 55]]


## More about Matrices

In [6]:
# matrix multiplicaiton
print("shapes of A and M:", A.shape, M.shape)
C1 = np.matmul(A, M)
C2 = A.dot(M)
C3 = A@M
print("C1 = \n", C1)
print("C2 = \n", C2)
print("C3 = \n", C3)

# matrix transpose
print("M^T = \n", np.transpose(M))
print("M^T = \n", M.transpose())


# matrix inverse
print("A^-1 = \n", np.linalg.inv(A))

shapes of A and M: (2, 2) (2, 3)
C1 = 
 [[ 16   7 -12]
 [ 17  16 -24]]
C2 = 
 [[ 16   7 -12]
 [ 17  16 -24]]
C3 = 
 [[ 16   7 -12]
 [ 17  16 -24]]
M^T = 
 [[  1  15]
 [  9  -2]
 [-12   0]]
M^T = 
 [[  1  15]
 [  9  -2]
 [-12   0]]
A^-1 = 
 [[-1.  1.]
 [ 2. -1.]]


## Vectors and Matrices

In [7]:
v = np.array([1,5,2,9])

# v
print("v", v.shape, " = ", v)

# row vector v
v = v.reshape(1,-1) # shape -1 in np.reshape means value is infered
print("row vector v", v.shape, " = ",  v) 

# column vector v
v = v.reshape(-1,1)
print("col vector v", v.shape, " = \n",  v) 

# matrix vector multiplication
A = np.array([[2,0],[0,1],[1,1]])
u = np.array([1,2])
print("u", u.shape, " = \n", u)
print("A", A.shape, " = \n", A)

print("Au = \n", A.dot(u))

u = u.reshape(-1,1)
print("u", u.shape, " = \n", u)
print("Au = \n", A.dot(u))


# inner product as matrix multiplication
vdotv = np.matmul(np.transpose(v), v)
print("v dot v =", vdotv)
print("shape of vdotv", vdotv.shape)

v (4,)  =  [1 5 2 9]
row vector v (1, 4)  =  [[1 5 2 9]]
col vector v (4, 1)  = 
 [[1]
 [5]
 [2]
 [9]]
u (2,)  = 
 [1 2]
A (3, 2)  = 
 [[2 0]
 [0 1]
 [1 1]]
Au = 
 [2 2 3]
u (2, 1)  = 
 [[1]
 [2]]
Au = 
 [[2]
 [2]
 [3]]
v dot v = [[111]]
shape of vdotv (1, 1)


## Calculate the exercises done in the morning, compare the results!

$X =\begin{bmatrix}
        1 & 2 & -1 \\ 1 & 0 & 1 \\
        \end{bmatrix}$ $Y =\begin{bmatrix}
        3 & 1 \\ 0 & -1 \\ -2 & 3
        \end{bmatrix}$ $Z = \begin{bmatrix}1\\4\\6\end{bmatrix}$ $A = \begin{bmatrix}
        1 & 2\\
        3 & 5
        \end{bmatrix}$ $ b= \begin{bmatrix}
        5 \\
        13
        \end{bmatrix}$


Calculate $XY$,  $YX$, $Z^TY$ and $A^{-1}b$

In [18]:
## To do
X = np.array([[1,2,-1], [1,0,1]])
print(X.shape)
Y = np.array([[3,1],[0,-1], [-2,3]])
print(Y.shape)
Z = np.array([1,4,6])
A = np.array([[1,2], [3,5]])
b = np.array([5,13])

print('---')
print(np.matmul(X,Y))
print('---')
print(np.matmul(Y,X))
print('---')
print(np.matmul(np.transpose(Z), Y))
print('---')
print(np.linalg.inv(A).dot(b))

(2, 3)
(3, 2)
---
[[ 5 -4]
 [ 1  4]]
---
[[ 4  6 -2]
 [-1  0 -1]
 [ 1 -4  5]]
---
[-9 15]
---
[1. 2.]
